In [1]:
from pathlib import Path
import sys
import json

project_root = Path.cwd().resolve().parents[1]
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

project_root

WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation')

In [2]:
config_path = project_root / "configs" / "datasets" / "public_dataset.json"

with open(config_path, "r", encoding="utf-8") as f:
    config = json.load(f)

public_root = Path(config["public_root"])

print("Public root exists:", public_root.exists())
print("Is directory:", public_root.is_dir())
print(public_root)

Public root exists: True
Is directory: True
C:\Users\P102832\Downloads\thesis_segmentation\data\raw\public_same_format\NIFTI

In [3]:
from src.eda.build_public_scan_inventory import find_nifti_files

files = find_nifti_files(public_root)
print("Number of NIfTI files found:", len(files))
files[:10]

Number of NIfTI files found: 274

[WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case101_day20.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case101_day22.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case101_day26.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case101_day32.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case102_day0.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case107_day0.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case107_day19.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case107_day21.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case108_day0.nii.gz'),
 WindowsPath('C:/Users/P102832/Downloads/thesis_segmentation/data/raw/public_same_format/NIFTI/case108_day10.nii.gz')]

In [4]:
from src.eda.build_public_scan_inventory import build_scan_inventory

df_public = build_scan_inventory(public_root)
df_public.head()

,scan_id,file_name,relative_path,parent_folder,suffix,num_dimensions,shape,shape_x,shape_y,shape_z,...,max_intensity,mean_intensity,std_intensity,median_intensity,p01_intensity,p05_intensity,p95_intensity,p99_intensity,nonzero_fraction,error
0,case101_day20,case101_day20.nii.gz,case101_day20.nii.gz,NIFTI,.nii.gz,3,"(266, 266, 144)",266,266,144,...,1909.0,51.326859,77.999893,12.0,0.0,0.0,233.0,331.0,0.865128,None
1,case101_day22,case101_day22.nii.gz,case101_day22.nii.gz,NIFTI,.nii.gz,3,"(266, 266, 144)",266,266,144,...,1954.0,63.634525,99.307228,15.0,0.0,0.0,296.0,426.0,0.860109,None
2,case101_day26,case101_day26.nii.gz,case101_day26.nii.gz,NIFTI,.nii.gz,3,"(266, 266, 144)",266,266,144,...,15495.0,781.417603,1165.488770,180.0,0.0,0.0,3480.0,4845.0,0.858829,None
3,case101_day32,case101_day32.nii.gz,case101_day32.nii.gz,NIFTI,.nii.gz,3,"(266, 266, 144)",266,266,144,...,1315.0,65.700104,105.351112,9.0,0.0,0.0,310.0,435.0,0.846061,None
4,case102_day0,case102_day0.nii.gz,case102_day0.nii.gz,NIFTI,.nii.gz,3,"(360, 310, 144)",360,310,144,...,3205.0,40.928844,77.998779,4.0,0.0,0.0,220.0,321.0,0.700228,None

In [5]:
df_public[["file_name", "shape", "spacing", "shape_x", "shape_y", "shape_z", "spacing_x", "spacing_y", "spacing_z"]].head(20)

,file_name,shape,spacing,shape_x,shape_y,shape_z,spacing_x,spacing_y,spacing_z
0,case101_day20.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
1,case101_day22.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
2,case101_day26.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
3,case101_day32.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
4,case102_day0.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
5,case107_day0.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
6,case107_day19.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
7,case107_day21.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
8,case108_day0.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
9,case108_day10.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
10,case108_day13.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
11,case110_day12.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
12,case110_day16.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
13,case111_day0.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
14,case111_day19.nii.gz,"(266, 266, 144)","(1.5, 1.5, 3.0)",266,266,144,1.5,1.5,3.0
15,case113_day0.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
16,case113_day12.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
17,case113_day16.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
18,case113_day19.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0
19,case113_day22.nii.gz,"(360, 310, 144)","(1.5, 1.5, 3.0)",360,310,144,1.5,1.5,3.0

In [6]:
df_public[df_public["error"].notna()].head(20)

Empty DataFrame
Columns: [scan_id, file_name, relative_path, parent_folder, suffix, num_dimensions, shape, shape_x, shape_y, shape_z, spacing, spacing_x, spacing_y, spacing_z, fov_x_mm, fov_y_mm, fov_z_mm, num_voxels, dtype, min_intensity, max_intensity, mean_intensity, std_intensity, median_intensity, p01_intensity, p05_intensity, p95_intensity, p99_intensity, nonzero_fraction, error]
Index: []

[0 rows x 30 columns]